blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view, 
    detail_blog_view,
    edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"), 
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
]





mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static 
from django.conf import settings

from personal.views import (
    home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('quizzes/', include(('quizzes.urls', 'quizzes'), namespace='quizzes')),

   
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizzes/urls.py
from django.urls import path
from . import views
from .views import create_quiz, quiz_list, all_students
from .views import student_grades


urlpatterns = [
    path('list/', views.quiz_list, name='quiz_list'),
    path('create/', create_quiz, name='create_quiz'),
    path('detail/<str:quiz_title>/', views.quiz_detail, name='quiz_detail'),
    path('all-students/', views.all_students, name='all_students'),
    path('student-detail/<int:student_id>/', views.student_detail, name='student_detail'),
    path('set-quiz-weight/', views.set_quiz_weight, name='set_quiz_weight'),
    path('student-grades/', student_grades, name='student-grades'),


]

templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #FFFFFF;
	}
</style>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<hr> 
<div class="d-flex flex-row align-items-center footer" >
	<p class="m-auto">Harsha's Online Learning System | Fall 2023</p>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

templates/snippets/header.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style type="text/css">
	@media (min-width: 768px) {
  		html {
    		font-size: 16px;
  		}
	}

	.container {
  	max-width: 960px;
	}

	.pricing-header {
  	max-width: 700px;
	}

	.card-deck .card {
  	min-width: 220px;
	}

	.search-bar{
		max-width: 500px;
		width: 100%;
	}

	form {
		width: 100%;
	}


</style>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
  	{% if request.user.is_authenticated %}
  	<p>Hello, {{request.user.username}}</p>
  	{% endif %}
  </h5>

  <div class="search-bar mt-sm-2 mr-2">
  	<form method="get">
  		<input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
  	</form>
  </div>



  <nav class="my-2 my-md-0 mr-md-3">
  	{% if request.user.is_authenticated %}
  		<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
		<a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
		<a class="p-2 text-dark" href="{% url 'quizzes:quiz_list' %}">Quizzes</a>
		<a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a></p>
  	{% else %}
  		<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
  		<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
		<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
  	{% endif %}
    
  </nav>
</div>

<script type="text/javascript">
	document.getElementById("id_q").value = {{query}}
</script>

